# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('PC', 'Participante'), ('OG', 'Organizador'), ('AU', 'Autor'), ('PR', 'Premio'), ('POG', 'Professor Organizador'), ('PA', 'Palestrante')], default='PC', max_length=50),
        ),
    ]
